<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="EPINHYDW0B79" failures="1" tests="3" name="Extent Report Test" time="0.219" errors="0" timestamp="2024-04-27T12:04:29 IST">
  <testcase classname="extentreports.ExtentTestCases" name="doLogin" time="0.049"/>
  <testcase classname="extentreports.ExtentTestCases" name="doSkip" time="0.006">
    <skipped/>
  </testcase> <!-- doSkip -->
  <testcase classname="extentreports.ExtentTestCases" name="doUserReg" time="0.023">
    <failure type="java.lang.AssertionError" message="Intentionally failing">
      <![CDATA[java.lang.AssertionError: Intentionally failing
at extentreports.ExtentTestCases.doUserReg(ExtentTestCases.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- doUserReg -->
</testsuite> <!-- Extent Report Test -->
